### ISSUE TITLE
NVDA: certificate has expired

### ISSUE THREAD

**Issue by nmerget** [guidepup/nvda#1]
# Issue

Setup:

- Node version: v20.16.0
- Guidepup version: 0.22.3
- OS Platform: windows

## Details

@cmorten 
Some certificate for NVDA expired. Maybe it's inside https://github.com/guidepup/nvda, but the error is thorwn [here](https://github.com/guidepup/guidepup/blob/44dda0133f371c728265565df940e737a9a4ed4d/src/windows/NVDA/NVDAClient.ts#L180). It rather works local nor in [GitHub Actions](https://github.com/db-ui/mono/actions/runs/12021936887/job/33513521155?pr=3511).

**Comment by jlp-craigmorten** [comment]
Thanks @nmerget for raising - this is now resolved in the latest version, meaning using `@guidepup/setup@latest` will now no longer install NVDA with an expired cert.

**Comment by nmerget** [comment]
[Works ](https://github.com/db-ui/mono/actions/runs/12113970946/job/33770183704?pr=3518) again. Thank you for your great job creating something like guidepup @jlp-craigmorten
